version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: sysadmin
      POSTGRES_PASSWORD: sysadmin123
      POSTGRES_DB: watchtower

    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "6432:6432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "8080:8080"
