version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sysadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watchtower
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    image: ghcr.io/mcdonaghmichael/watchtower-api:latest
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_USER: sysadmin
      DB_PASSWORD: password
      DB_NAME: watchtower
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ALLOWED_ORIGIN: 13.61.182.15
    ports:
      - "8080:8080"
